# Generated by Django 2.1.7 on 2019-02-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_storeitem_description_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='item_pics'),
        ),
    ]
