# Generated by Django 2.1.7 on 2019-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_storeitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_to_card', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item_to_buy',
            field=models.ManyToManyField(null=True, to='webstore.StoreItem'),
        ),
    ]
