# Generated by Django 2.1.7 on 2019-02-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0005_auto_20190228_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='item_to_buy',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
